package redislock

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net"
	"os"
	"sync/atomic"
	"time"

	"github.com/go-lynx/lynx/log"
)

// lockValuePrefix is the process-unique prefix (host-ip-pid) shared by every
// lock value generated by this process; computed once at init.
var lockValuePrefix string

// sequenceNum is bumped atomically to make each lock value unique within the process.
var sequenceNum uint64

func init() {
	lockValuePrefix = generateLockValuePrefix()
}

func generateLockValuePrefix() string {
	hostname := getHostnameWithRetry()
	ip := getLocalIPWithRetry()
	return fmt.Sprintf("%s-%s-%d-", hostname, ip, os.Getpid())
}

func getHostnameWithRetry() string {
	const maxRetries = 3
	for i := 0; i < maxRetries; i++ {
		hostname, err := os.Hostname()
		if err == nil {
			return hostname
		}
		log.ErrorCtx(context.Background(), "failed to get hostname", "attempt", i+1, "error", err)
		if i < maxRetries-1 {
			time.Sleep(time.Duration(1<<i) * 100 * time.Millisecond)
		}
	}
	return "unknown-host"
}

// getLocalIPWithRetry gets local IP with retry mechanism
func getLocalIPWithRetry() string {
	const maxRetries = 3
	for i := 0; i < maxRetries; i++ {
		addrs, err := net.InterfaceAddrs()
		if err == nil {
			for _, addr := range addrs {
				if ipnet, ok := addr.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
					if ipv4 := ipnet.IP.To4(); ipv4 != nil {
						return ipv4.String()
					}
				}
			}
			break
		}
		log.ErrorCtx(context.Background(), "failed to get interface addresses", "attempt", i+1, "error", err)
		if i < maxRetries-1 {
			time.Sleep(time.Duration(1<<i) * 100 * time.Millisecond)
		}
	}
	return "unknown-ip"
}

// generateLockValue returns a globally unique lock value of the form
// prefix-seq-randomhex, used to prove ownership during release/renew. If the CSPRNG
// is unavailable it falls back to a timestamp so acquisition never blocks.
func generateLockValue() string {
	seq := atomic.AddUint64(&sequenceNum, 1)
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return fmt.Sprintf("%s%d-%d", lockValuePrefix, seq, time.Now().UnixNano())
	}
	token := hex.EncodeToString(b[:])
	return fmt.Sprintf("%s%d-%s", lockValuePrefix, seq, token)
}
